'use client';
import {DragEvent,FormEvent,useEffect,useRef,useState,use} from 'react';import Link from 'next/link';import {api,downloadFile,uploadFile} from '@/lib/api';
type Node={id:string;type:'folder'|'document'|'file';name:string;file?:{size_bytes:number;current_version?:{extraction_status:string}}};
export default function Browse({params}:{params:Promise<{workspace:string}>}){
 const {workspace}=use(params);const [nodes,setNodes]=useState<Node[]>([]);const [error,setError]=useState('');const [progress,setProgress]=useState<number|null>(null);const input=useRef<HTMLInputElement>(null);
 const load=()=>api<Node[]>(`/workspaces/${workspace}/nodes`).then(setNodes).catch(e=>setError(String(e)));useEffect(()=>{load()},[workspace]);
 async function folder(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await api(`/workspaces/${workspace}/folders`,{method:'POST',body:JSON.stringify({name:f.get('name')})});e.currentTarget.reset();load()}
 async function doc(){await api(`/workspaces/${workspace}/documents`,{method:'POST',body:JSON.stringify({name:'Untitled document',plain_text:'Start writing your company knowledge here.'})});load()}
 async function send(file:File){setError('');setProgress(0);try{await uploadFile(`/workspaces/${workspace}/files`,file,null,setProgress);await load()}catch(e){setError(String(e))}finally{setProgress(null);if(input.current)input.current.value=''}}
 function drop(e:DragEvent){e.preventDefault();const file=e.dataTransfer.files?.[0];if(file)send(file)}
 return <div className="grid"><aside className="sidebar stack"><h2>Dataroom</h2><Link href={`/w/${workspace}/browse`}>Browse</Link><Link href={`/w/${workspace}/search`}>Search</Link></aside><main className="main"><div className="topbar"><div><h1>Company knowledge</h1><p className="muted">Folders, documents and files share one tree.</p></div><div className="row"><input ref={input} type="file" hidden onChange={e=>{const f=e.target.files?.[0];if(f)send(f)}}/><button className="btn secondary" onClick={()=>input.current?.click()}>↑ Upload</button><button className="btn" onClick={doc}>+ Document</button></div></div><form className="row" onSubmit={folder}><input className="input" name="name" placeholder="New folder name"/><button className="btn secondary">+ Folder</button></form><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={drop} onClick={()=>input.current?.click()}><b>Drop a file here</b><span className="muted"> or click to upload · PDF, DOCX, text and other files</span>{progress!==null&&<div className="progress"><span style={{width:`${progress}%`}}/></div>}</div><div className="card" style={{marginTop:20}}>{nodes.map(n=><div className="node" key={n.id}><span>{n.type==='folder'?'📁':n.type==='document'?'📄':'📎'} {n.name}</span><div className="row">{n.type==='file'&&<><small className="muted">{n.file?.current_version?.extraction_status??'pending'}</small><button className="linkButton" onClick={()=>downloadFile(n.id,n.name)}>Download</button></>}<small className="muted">{n.type}</small></div></div>)}{!nodes.length&&<p className="muted">Nothing here yet.</p>}</div>{error&&<pre>{error}</pre>}</main></div>
}
