<?php
use Illuminate\Database\Migrations\Migration; use Illuminate\Database\Schema\Blueprint; use Illuminate\Support\Facades\Schema;
return new class extends Migration {
 public function up(): void {
  Schema::create('workspaces', function(Blueprint $t){$t->uuid('id')->primary();$t->string('name');$t->string('slug')->unique();$t->uuid('owner_user_id');$t->unsignedBigInteger('storage_quota_bytes')->default(107374182400);$t->timestamps();$t->foreign('owner_user_id')->references('id')->on('users')->cascadeOnDelete();});
  Schema::create('workspace_members', function(Blueprint $t){$t->uuid('workspace_id');$t->uuid('user_id');$t->string('role',20)->default('member');$t->timestamps();$t->primary(['workspace_id','user_id']);$t->foreign('workspace_id')->references('id')->on('workspaces')->cascadeOnDelete();$t->foreign('user_id')->references('id')->on('users')->cascadeOnDelete();});
  Schema::create('nodes', function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('workspace_id');$t->uuid('parent_id')->nullable();$t->string('type',20);$t->string('name');$t->string('slug');$t->uuid('created_by');$t->timestamps();$t->softDeletes();$t->index(['workspace_id','parent_id']);$t->index(['workspace_id','type']);$t->foreign('workspace_id')->references('id')->on('workspaces')->cascadeOnDelete();$t->foreign('parent_id')->references('id')->on('nodes')->cascadeOnDelete();$t->foreign('created_by')->references('id')->on('users')->cascadeOnDelete();});
  Schema::create('documents', function(Blueprint $t){$t->uuid('node_id')->primary();$t->jsonb('content_json');$t->text('plain_text')->default('');$t->string('status',20)->default('draft');$t->uuid('owner_user_id')->nullable();$t->unsignedInteger('version')->default(1);$t->timestamps();$t->foreign('node_id')->references('id')->on('nodes')->cascadeOnDelete();$t->foreign('owner_user_id')->references('id')->on('users')->nullOnDelete();});
  Schema::create('document_revisions', function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('node_id');$t->unsignedInteger('version');$t->jsonb('content_json');$t->text('plain_text')->default('');$t->uuid('created_by');$t->timestampTz('created_at')->useCurrent();$t->unique(['node_id','version']);$t->foreign('node_id')->references('id')->on('nodes')->cascadeOnDelete();});
  Schema::create('files', function(Blueprint $t){$t->uuid('node_id')->primary();$t->uuid('current_version_id')->nullable();$t->string('mime_type')->nullable();$t->unsignedBigInteger('size_bytes')->default(0);$t->timestamps();$t->foreign('node_id')->references('id')->on('nodes')->cascadeOnDelete();});
  Schema::create('file_versions', function(Blueprint $t){$t->uuid('id')->primary();$t->uuid('node_id');$t->unsignedInteger('version');$t->string('object_key')->unique();$t->string('mime_type');$t->unsignedBigInteger('size_bytes');$t->string('sha256',64)->nullable();$t->longText('extracted_text')->nullable();$t->uuid('created_by');$t->timestampTz('created_at')->useCurrent();$t->unique(['node_id','version']);$t->foreign('node_id')->references('id')->on('nodes')->cascadeOnDelete();});
 }
 public function down(): void { foreach(['file_versions','files','document_revisions','documents','nodes','workspace_members','workspaces'] as $table) Schema::dropIfExists($table); }
};
